version: '3.8'

services:
  similarwords:
    build:
      context: ..
      dockerfile: ./devops/Dockerfile
    image: markliau/similarwords:v1.0
    ports:
      - "6080:8080"
    environment:
      - DbConnection=${DbConnection}
      - OidcJwt__Authority=${OidcJwt__Authority}
      - GeminiAi__ApiBaseUrl=your_gemini_api_url

